### ISSUE TITLE
Missing layers in GIS Project

### ISSUE THREAD

**Issue by markjessell** [dhasterok/global_tectonics#2]
Great resource!!

**Describe the bug**

I donloaded the zip package from Zenodo and fired up the qgis project and the following layers are missing, perhaps intentionally, but maybe better to remove them for general consumption?

Missing layers:

cratons
global_geochemistry_cao
ne_10m_graticules
ne_10m_gs4_bounding_box
antarctica

**To Reproduce**
Open global_tectonics.qgz

**Expected behavior**
all layers in qgis project are available

**Comment by dhasterok** [comment]
Mark, thanks for reporting the missing files in the Zenodo version.  I'll add or remove them from the project file once reviews come back (the manuscript has been in review for just under two months now).  I'd like to see what other changes reviewers would like and just make all those updates at once.

**Comment by markjessell** [comment]
sounds good, thanks again for assembling this

**Comment by dhasterok** [comment]
The Zenodo files have been updated.
